### ISSUE TITLE
[Question] Use "DOCKER_AUTH_CONFIG" as possible input for the JSON value of Docker config

### ISSUE THREAD

**Issue by mdelapenya** [cpuguy83/dockercfg#2]
Hi 👋 I want to open a discussion about the different inputs that certain CI services (e.g. Gitlab CI) provides when reading the Docker config.

First, this library satisfies all our needs regarding automatically loading the Docker config, so thanks for creating it 🙏 

Second, we could see convenient, as a possible feature request, that the library would read the `DOCKER_AUTH_CONFIG` variable, reading that string as a JSON object and applying it as the Docker config.

This potential feature could be handy for scenarios where the Docker config can be obtained from that variable. Please Gitlab CI docs on this topic: https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#use-statically-defined-credentials

We at Testcontainers are actually reading the variable in some of our lang implementations ([.NET](https://github.com/testcontainers/testcontainers-dotnet/blob/7b6e0ae35833c29db79ddedefa653edaa30c0525/docs/custom_configuration/index.md?plain=1#L9) and [Java](https://github.com/testcontainers/testcontainers-java/blob/8b5119b49b189b47394060e3bdb9e759e8f8fdc1/core/src/main/java/org/testcontainers/utility/RegistryAuthLocator.java#L186-L188)), as our users run their own tests in those CI services, coming to us asking for that capability. Now that the Go implementation needs something similar (see https://github.com/testcontainers/testcontainers-go/pull/869) we considered opening this discussion first. We could add it ourselves to Testcontainers of course, but we think it could be interesting opening the discussion with the maintainers of this library in the case it's also interesting here.

If there is interest, we could elaborate a PR with the possible changes, just let us know your thoughts.

Cheers!

**Comment by cpuguy83** [comment]
Thanks for opening this.

I feel like this is better suited outside this library, mostly because different callers may want different merging strategies.
Maybe if the docker CLI supported this in a specific way it would make more sense here?

**Comment by mdelapenya** [comment]
Indeed, I'd have expected docker binary to handle it transparently... 🤷‍♂️

In any case, I think it's fine if we implement it in our own library.

Thanks for your feedback

**Comment by mdelapenya** [comment]
@cpuguy83 I appreciate your time answering this question 🙇 We finally implemented it in our own library https://github.com/testcontainers/testcontainers-go/pull/869/files#diff-f7bd0a6d4a5162f57983fa95c903abe3f76d8792ed3acd6b4338fd6f6c3df584R20-R33

So I think we can close this issue.

Thank you very much for your time!
